#!/usr/bin/env python3
"""Regenerates tests/license_test_vector.h.

Creates a throwaway P-256 key with OpenSSL, signs a proof body, and writes the
public key, the body, and the signature as raw r‖s. The committed header lets the
licence test run anywhere without OpenSSL; run this only if you want a fresh vector.

    python3 tools/make_license_test_vector.py
"""
import base64, json, os, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "tests", "license_test_vector.h")

def der_sig_to_raw(der):
    assert der[0] == 0x30, "expected a DER SEQUENCE"
    i = 2 if der[1] < 0x80 else 2 + (der[1] & 0x7F)
    def read_int(i):
        assert der[i] == 0x02, "expected a DER INTEGER"
        length = der[i + 1]
        value = der[i + 2:i + 2 + length]
        return value.lstrip(b"\x00").rjust(32, b"\x00"), i + 2 + length
    r, i = read_int(i)
    s, _ = read_int(i)
    return r + s

def main():
    with tempfile.TemporaryDirectory() as tmp:
        priv = os.path.join(tmp, "priv.pem")
        subprocess.run(["openssl", "ecparam", "-name", "prime256v1", "-genkey",
                        "-noout", "-out", priv], check=True, capture_output=True)

        body = json.dumps({
            "deviceKey": "3f7c2a9e-6b1d-4e2f-9a8c-1d2e3f4a5b6c",
            "licenseKey": "AETH-1111-2222-3333",
            "issuedAt": 1757289600000,
            "expiresAt": 1757462400000,
            "graceUntil": 1759881600000,
        }, separators=(",", ":")).encode()

        body_path = os.path.join(tmp, "body.json")
        with open(body_path, "wb") as f:
            f.write(body)

        der = subprocess.run(["openssl", "dgst", "-sha256", "-sign", priv, body_path],
                             check=True, capture_output=True).stdout
        raw_sig = der_sig_to_raw(der)

        pub_der = subprocess.run(["openssl", "ec", "-in", priv, "-pubout", "-outform", "DER"],
                                 check=True, capture_output=True).stdout
        pub = pub_der[-65:]
        assert pub[0] == 0x04, "expected an uncompressed SEC1 point"

    def as_c_array(data):
        return ",\n    ".join(", ".join(f"0x{b:02x}" for b in data[i:i + 12])
                              for i in range(0, len(data), 12))

    b64url = lambda b: base64.urlsafe_b64encode(b).decode().rstrip("=")
    proof = f"{b64url(body)}.{b64url(raw_sig)}"

    with open(OUT, "w") as f:
        f.write(f'''// Generated by tools/make_license_test_vector.py — do not edit by hand.
// A throwaway P-256 key, a proof body, and its signature as raw r-s. Used to prove the
// platform verification path accepts a good proof and rejects tampered ones.
#pragma once
#include <cstdint>

namespace aether::license::testvector
{{

inline constexpr std::uint8_t publicKey[65] = {{
    {as_c_array(pub)}
}};

inline constexpr std::uint8_t body[{len(body)}] = {{
    {as_c_array(body)}
}};

inline constexpr std::uint8_t signature[64] = {{
    {as_c_array(raw_sig)}
}};

inline constexpr const char* proof = "{proof}";
inline constexpr const char* expectedDeviceKey  = "3f7c2a9e-6b1d-4e2f-9a8c-1d2e3f4a5b6c";
inline constexpr const char* expectedLicenseKey = "AETH-1111-2222-3333";

}} // namespace aether::license::testvector
''')
    print(f"wrote {os.path.normpath(OUT)}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
